/*PCA*/
ods graphics on;
/*Correlation*/
proc corr data=wine_imputed;
	VAR WINE_PREFERENCE--WINE_COURSE SUPERMARKET--PROMOTION PARTY--ETNA_RECOMMENDATION;
run;
/*PCA*/
proc princomp data=wine_imputed;
	VAR WINE_PREFERENCE--WINE_COURSE SUPERMARKET--PROMOTION PARTY--ETNA_RECOMMENDATION;
run;
proc princomp data=wine_imputed OUT=DF_PCA OUTSTAT=DF_EIGENX N=11;
	VAR WINE_PREFERENCE--WINE_COURSE SUPERMARKET--PROMOTION PARTY--ETNA_RECOMMENDATION;
run;
/*CORRELATION OF PCs WITH THE ORIGINAL VARIABLES*/
PROC CORR DATA=DF_PCA noprint OUT=PCA_CORR(WHERE=(_TYPE_='CORR'));
VAR prin1--prin11; 
WITH WINE_PREFERENCE--WINE_COURSE SUPERMARKET--PROMOTION PARTY--ETNA_RECOMMENDATION;
RUN;
PROC PRINT DATA=PCA_CORR ROUND ;
RUN;
proc plot data=DF_PCA;
plot prin2*prin1;
run;
